//
//  Games.swift
//  TableTopMeetUp
//
//  Created by Tyler Donohue on 2/11/19.
//  Copyright © 2019 Tyler Donohue. All rights reserved.
//

import Foundation

struct Games {
    
    static let name = [
        
        // MARK: - Two-player games
        "Abalone",
        "Agon",
        "Android: Netrunner",
        "Android",
        "Asalto",
        "Backgammon",
        "BattleLore",
        "Battleship",
        "Blockade",
        "Blood Bowl",
        "Bul",
        "Camelot",
        "Chaturanga",
        "Checkers",
        "Chess",
        "Commands & Colors: Ancients",
        "Connect 4",
        "Cross and Circle game",
        "Daldøs",
        "Diamond",
        "Diceball",
        "Downfall",
        "DVONN",
        "Fanorona",
        "Game of the Generals",
        "Ghosts",
        "Go",
        "Gipf",
        "Guess Who?",
        "Hare and Hounds",
        "Hounds and Jackals",
        "Hex",
        "Hijara",
        "Isola",
        "Janggi",
        "Jaipur",
        "Le Jeu de la Guerre",
        "Kalah",
        "Kamisado",
        "Liu po",
        "Lost Cities",
        "Mad Gab",
        "Makruk",
        "Master Mind",
        "Matching game",
        "Nine men's morris",
        "Onyx",
        "Operation",
        "Ouk Chatrang",
        "Plateau",
        "PÜNCT",
        "Quarto",
        "Qwirkle",
        "Rithmomachy",
        "Sáhkku",
        "Sahkku",
        "Santorini",
        "Sector 41",
        "Senet",
        "Shatar",
        "Shatranj",
        "Shogi",
        "Simon",
        "Sittuyin",
        "Skip-Bo",
        "Space Hulk",
        "Star Wars: X-Wing Miniatures Game",
        "Star Wars",
        "Stratego",
        "Sugoroku",
        "Ta Yü",
        "Tâb",
        "Tablut",
        "Tantrix",
        "Tak",
        "Twilight Struggle",
        "Wari",
        "Wooper",
        "Xiangqi",
        "YINSH",
        "ZÈRTZ",
        "Zingo!",
        
        // MARK: - Multi-player elimination games
        "13 Dead End Drive",
        "1313 Dead End Drive",
        "American Megafauna",
        "Anti-Monopoly",
        "Attack!",
        "Axis & Allies",
        "Bang!",
        "Battle Sheep",
        "Betrayal at House on the Hill",
        "Blokus",
        "Blood Feud in New York",
        "Blue Max",
        "Bookchase",
        "Castle Risk",
        "Clue Jr.: Case of the Missing Pet",
        "Coppit",
        "Diplomacy",
        "Djambi",
        "Doom: The Boardgame",
        "Eclipse",
        "The Farming Game",
        "Finance",
        "Ghettopoly",
        "Glückshaus",
        "The Great Train Robbery",
        "Heroscape",
        "Hey, That's My Fish!",
        "Hotels",
        "Jenga",
        "Khet",
        "King of Tokyo",
        "King Oil",
        "Ludo",
        "Mikado",
        "Poleconomy",
        "Risk",
        "Shadow Hunters",
        "Shengguan Tu",
        "Shogun/Samurai Swords",
        "Solarquest",
        "Spy Alley",
        "Star Wars Epic Duels",
        "Star Wars Tactics",
        "StarCraft: The Board Game",
        "Strange Synergy",
        "Summit",
        "TEG",
        "Titan",
        "Tsuro",
        "Tsuro of the Seas",
        "War on Terror",
        
        // MARK: -
        "Cartagena",
        "Chicken Cha Cha Cha",
        "Formula Dé",
        "Game of the Goose",
        "Hare and Tortoise",
        "Mississippi Queen",
        "Transformers",
        
        // MARK: - European race games
        "18XX",
        "221B Baker Street",
        "30 Seconds",
        "About Time",
        "Acquire",
        "Acronymble",
        "Adel Verpflichtet",
        "Afrikan tähti",
        "Agricola",
        "Air Charter",
        "Aksharit",
        "Aladdin's Dragons",
        "Alhambra",
        "Alias",
        "Amun-Re",
        "Arkham Horror",
        "Articulate!",
        "Ashta Chamma",
        "Auf Achse",
        "Australia",
        "Azul",
        "Bailout! The Game",
        "Balderdash",
        "Barbarossa",
        "Battlestar Galactica",
        "Bezzerwizzer",
        "Blankety Blank",
        "Blokus",
        "Blood Rage",
        "(This Game Is) Bonkers!",
        "Brain Chain",
        "Brainstorm",
        "Break the Safe",
        "Buccaneer",
        "Camel Up",
        "Candy Land",
        "Can't Stop",
        "Capitol",
        "Carcassonne",
        "Careers",
        "Caribbean",
        "Cartagena",
        "Caylus",
        "Chinese Chequers",
        "Chromino",
        "CirKis",
        "Civilization",
        "Clans",
        "Clue/Cluedo",
        "Codenames",
        "Coin Hopping—Washington D.C.",
        "Colt Express",
        "Concept",
        "Conspiracy",
        "Cosmic Encounter",
        "Cranium",
        "Crosstrack",
        "Dark Tower",
        "Dead of Winter: A Cross Roads Game",
        "Diamant",
        "Dixit",
        "Domaine",
        "Dominion",
        "Don't Miss the Boat",
        "Don't Quote Me",
        "Dorn",
        "Drunter und Drüber",
        "Dune",
        "Dungeons & Dragons",
        "El Grande",
        "Elfenland",
        "Enchanted Forest",
        "Entdecker",
        "Escape from Atlantis",
        "Farlander",
        "Fictionary",
        "Figure It Out",
        "Fireball Island",
        "Focus",
        "Fresco",
        "Game For Fame",
        "The Game of Life",
        "GiftTRAP",
        "Giganten",
        "Girl Talk",
        "Glasnost The Game",
        "Go",
        "Great Train Robbery",
        "GridIron Master",
        "Halma",
        "History of the World",
        "Hooop!",
        "Husker Du?",
        "I'm the Boss!",
        "Imperial",
        "Indigo",
        "Ingenious",
        "Inkan aarre",
        "Java",
        "Journey through Europe",
        "Junta",
        "Karuba",
        "Keltis",
        "Kill Doctor Lucky",
        "Kingdomino",
        "Kingdoms",
        "Landslide",
        "Las Vegas",
        "Le Havre",
        "The Game of Life",
        "Logo Board Game",
        "The London Game",
        "Lords of Waterdeep",
        "Löwenherz",
        "Luck of the Draw",
        "Die Macher",
        "The Mad Magazine Game",
        "The Magic Labyrinth",
        "Mahjong",
        "Malefiz",
        "Mall Madness",
        "Manhattan",
        "Master Labyrinth",
        "Masterpiece",
        "Medici",
        "Medina",
        "Mensch ärgere dich nicht",
        "Merchant of Venus",
        "Mexica",
        "Mine a million",
        "Modern Art",
        "Mutant Meeples",
        "Near and Far",
        "Niagara",
        "Okey",
        "Omega Virus",
        "Ouija",
        "Outrage!",
        "Pack & Stack",
        "Pandemic",
        "Parcheesi",
        "Parqués",
        "Pay Day",
        "Personal Preference",
        "Pictionary",
        "Pirate's Cove",
        "Power Grid",
        "Primordial Soup",
        "Princes of Florence",
        "Probe",
        "Puerto Rico",
        "Puzzle",
        "Qin",
        "The Quest of the Philosopher's Stone",
        "Quoridor",
        "Qwirkle",
        "Ra",
        "Rail Baron",
        "Rappakalja",
        "Razzia",
        "Ricochet Robots",
        "Rivers, Roads & Rails",
        "RoboRally",
        "Rummikub",
        "Rummoli",
        "Saint Petersburg",
        "Samurai",
        "San Marco",
        "Scattergories",
        "Scene It",
        "Scotland Yard",
        "Scoundrels of Skullport",
        "Scrabble",
        "Scythe",
        "Sequence",
        "The Settlers of Catan",
        "Shadows over Camelot",
        "Sherlock Holmes: Consulting Detective",
        "Skirrid",
        "Small World",
        "Snakes and Ladders",
        "Sorry!",
        "Splendor",
        "Squatter",
        "Stock Ticker",
        "Taj Mahal",
        "Take It Easy",
        "Take Off!",
        "Take the Galaxy",
        "Terraforming Mars",
        "Terra Mystica",
        "Through the Ages",
        "Through the Desert",
        "Thurn and Taxis",
        "Ticket to Ride",
        "Tigris and Euphrates",
        "Tikal",
        "Timberland",
        "Time's Up!",
        "Top Secret Spies",
        "Torres",
        "Totopoly",
        "Tracks to Telluride",
        "TransAmerica",
        "Trivial Pursuit",
        "Trouble",
        "Twilight Imperium",
        "Twin Tin Bots",
        "Ubongo",
        "Upwords",
        "Vanished Planet",
        "Vinci",
        "Wingspan",
        "Yahtzee",
        "Yut",
        "Zombies!!!",
        "Zoophoria",
        
        // MARK: - Economics and strategy games
        "Battleship",
        "Diplomacy",
        "Glasnost The Game",
        "Junta",
        "Kolejka",
        "København",
        "Monopoly",
        "Power Grid",
        "Race for the Galaxy",
        "Risk",
        "Risk 2210 AD",
        "Sentinels of the Multiverse",
        "Squatter",
        "The Settlers of Catan",
        "Ticket to Ride",

        // MARK: - Games of physical skill
        "Blockhead!",
        "Buckaroo",
        "Camp Granada",
        "Carrom",
        "Chapayev",
        "Crokinole",
        "Dart Wars",
        "Gnip Gnop",
        "Hungry Hungry Hippos",
        "Jenga",
        "Kerplunk",
        "Krazy Maze",
        "Operation",
        "Perfection",
        "Polarity",
        "Subbuteo",
        "Twister",
        "Villa Paletti",
        
        // MARK: - Children's games
        "Candy Land",
        "Catan Junior",
        "Chicken Cha Cha Cha",
        "Don't Break the Ice",
        "Don't Wake Daddy",
        "Forbidden Bridge",
        "Hey Pa! There's a Goat on the Roof",
        "Hi Ho! Cherry-O",
        "Hungry Hungry Hippos",
        "The Kids of Catan",
        "Ludo",
        "Mouse Trap",
        "Snakes and ladders (aka Chutes and Ladders)",
        "Sorry!",
        "Space Hop",
        "Uncle Wiggily",
        
        // MARK: - Cooperative games
        "Arkham Horror",
        "Battlestar Galactica: The Board Game",
        "Betrayal at House on the Hill",
        "Castle Panic",
        "Flash Point",
        "Forbidden Island",
        "Freedom: The Underground Railroad",
        "Gloomhaven",
        "Hanabi",
        "Just One",
        "Lord of the Rings",
        "Pandemic",
        "Sentinels of the Multiverse",
        "Shadows over Camelot",
        "Space Alert",
        "X-COM",
        
        // MARK: - Word games
        "25 Words or Less",
        "Acronymble",
        "Aksharit",
        "Alfapet",
        "Bananagrams",
        "Big Taboo",
        "Kings Cribbage",
        "Mad Gab",
        "Pictionary",
        "Probe",
        "Scrabble",
        "Thiruthamizh",
        "Trickster",
        "UpWords",
        "Words with Friends",
        
        // MARK: - Gaming systems
        "Flibbix",
        "Hanafuda",
        "Icehouse pieces",
        "Stonehenge",
        
        // MARK: - ONLINE GAMES
        // MARK: - MMORPG
        
        // MARK: - Mobile Games
        
        // MARK: - ??????
        "Barbie Dream House"

    ]
}
